import type { RuntimeSfxAsset, SfxCue } from '../data/audioAssets';
import {
  BASE_AMBIENCE_PROFILE,
  DRAG_TEXTURE_PROFILE,
  getAudioCuePresentationDirective,
  getChipPitchMultiplier,
  getOneShotPitchVariation,
  getDragTextureMix,
  getRarityAmbienceProfile,
  getRevealAnticipationAudioProfile,
  type PersistentResultAmbience,
  type ResultAmbienceRarity,
} from '../data/audioPresentation';

export type { SfxCue } from '../data/audioAssets';

interface ToneSpec {
  frequency: number;
  endFrequency?: number;
  duration: number;
  type: OscillatorType;
  gain: number;
  delay?: number;
}

const CUES: Readonly<Record<SfxCue, readonly ToneSpec[]>> = {
  tear: [
    { frequency: 260, endFrequency: 105, duration: 0.1, type: 'sawtooth', gain: 0.035 },
    { frequency: 690, endFrequency: 330, duration: 0.07, type: 'square', gain: 0.018, delay: 0.045 },
  ],
  'reveal-pop': [{ frequency: 180, endFrequency: 520, duration: 0.11, type: 'sine', gain: 0.055 }],
  common: [{ frequency: 520, duration: 0.12, type: 'sine', gain: 0.035 }],
  rare: [
    { frequency: 560, duration: 0.12, type: 'sine', gain: 0.036 },
    { frequency: 720, duration: 0.14, type: 'sine', gain: 0.03, delay: 0.07 },
  ],
  epic: [
    { frequency: 610, duration: 0.13, type: 'triangle', gain: 0.038 },
    { frequency: 820, duration: 0.15, type: 'sine', gain: 0.032, delay: 0.07 },
    { frequency: 1040, duration: 0.17, type: 'sine', gain: 0.026, delay: 0.14 },
  ],
  legendary: [
    { frequency: 650, duration: 0.16, type: 'triangle', gain: 0.04 },
    { frequency: 880, duration: 0.18, type: 'sine', gain: 0.035, delay: 0.08 },
    { frequency: 1180, duration: 0.22, type: 'sine', gain: 0.03, delay: 0.16 },
  ],
  duplicate: [
    { frequency: 260, endFrequency: 170, duration: 0.075, type: 'square', gain: 0.022 },
    { frequency: 1180, endFrequency: 640, duration: 0.055, type: 'triangle', gain: 0.014, delay: 0.018 },
  ],
  'new-discovery': [
    { frequency: 740, endFrequency: 980, duration: 0.1, type: 'triangle', gain: 0.028 },
    { frequency: 1110, duration: 0.13, type: 'sine', gain: 0.025, delay: 0.065 },
    { frequency: 1480, duration: 0.16, type: 'sine', gain: 0.018, delay: 0.125 },
  ],
  'ui-click': [
    { frequency: 880, endFrequency: 690, duration: 0.038, type: 'square', gain: 0.022 },
    { frequency: 1280, duration: 0.026, type: 'triangle', gain: 0.012, delay: 0.012 },
  ],
  'ui-skip': [
    { frequency: 1480, endFrequency: 920, duration: 0.042, type: 'square', gain: 0.026 },
    { frequency: 1840, duration: 0.026, type: 'triangle', gain: 0.015, delay: 0.018 },
  ],
  'carousel-switch': [
    { frequency: 720, endFrequency: 810, duration: 0.038, type: 'triangle', gain: 0.014 },
    { frequency: 1080, endFrequency: 980, duration: 0.026, type: 'sine', gain: 0.008, delay: 0.012 },
  ],
  'pouch-select': [
    { frequency: 520, endFrequency: 720, duration: 0.055, type: 'triangle', gain: 0.026 },
    { frequency: 920, endFrequency: 1080, duration: 0.045, type: 'sine', gain: 0.018, delay: 0.035 },
  ],
  // `pouch-grab` is generated by schedulePouchGrab for a short plastic zip/pop transient.
  'pouch-grab': [],
  'ui-denied': [
    { frequency: 250, endFrequency: 185, duration: 0.055, type: 'square', gain: 0.025 },
    { frequency: 190, endFrequency: 150, duration: 0.05, type: 'triangle', gain: 0.02, delay: 0.045 },
  ],
  'charged-spend': [
    { frequency: 980, endFrequency: 430, duration: 0.085, type: 'square', gain: 0.024 },
    { frequency: 360, endFrequency: 250, duration: 0.09, type: 'triangle', gain: 0.022, delay: 0.025 },
  ],
  // `chip-clack` is generated by scheduleChipClack so it can sound percussive
  // without requiring an unreviewed binary sample.
  'chip-clack': [],
  'signal-gain': [{ frequency: 780, endFrequency: 920, duration: 0.09, type: 'square', gain: 0.018 }],
  'signal-lock': [
    { frequency: 450, endFrequency: 900, duration: 0.18, type: 'square', gain: 0.025 },
    { frequency: 1120, duration: 0.16, type: 'sine', gain: 0.028, delay: 0.14 },
  ],
  'hidden-pocket': [
    { frequency: 350, endFrequency: 760, duration: 0.15, type: 'triangle', gain: 0.035 },
    { frequency: 980, endFrequency: 620, duration: 0.2, type: 'sine', gain: 0.025, delay: 0.11 },
  ],
  'secret-reveal': [
    { frequency: 720, duration: 0.18, type: 'triangle', gain: 0.04 },
    { frequency: 1080, duration: 0.24, type: 'sine', gain: 0.035, delay: 0.09 },
    { frequency: 1440, duration: 0.28, type: 'sine', gain: 0.028, delay: 0.18 },
  ],
  'collection-complete': [
    { frequency: 523, duration: 0.13, type: 'sine', gain: 0.032 },
    { frequency: 659, duration: 0.13, type: 'sine', gain: 0.032, delay: 0.09 },
    { frequency: 784, duration: 0.2, type: 'sine', gain: 0.032, delay: 0.18 },
  ],
};

class GameAudioController {
  private context: AudioContext | null = null;
  private readonly samples = new Map<SfxCue, AudioBuffer>();
  private chipNoiseBuffer: AudioBuffer | null = null;
  private ambienceNoiseBuffer: AudioBuffer | null = null;
  private baseAmbienceBus: GainNode | null = null;
  private persistentRarityBus: GainNode | null = null;
  private persistentRarityToneFilter: BiquadFilterNode | null = null;
  private persistentRarityShimmerGain: GainNode | null = null;
  private persistentRaritySources: AudioScheduledSourceNode[] = [];
  private activeResultAmbience: PersistentResultAmbience | null = null;
  private desiredResultAmbience: PersistentResultAmbience | null = null;
  private resultAmbienceTimer: number | null = null;
  private steadyBaseMultiplier = 1;
  private dragTextureSource: AudioBufferSourceNode | null = null;
  private dragTextureFilter: BiquadFilterNode | null = null;
  private dragTextureGain: GainNode | null = null;
  private dragTextureIdleTimer: number | null = null;
  private dragTextureEnvelopeStartedAt: number | null = null;
  private muted = false;
  private blocked = false;

  public isMuted(): boolean {
    return this.muted;
  }

  public setMuted(muted: boolean): void {
    this.muted = muted;
    if (muted) this.stopDragTexture(true);
    if (muted && this.context?.state === 'running') {
      void this.context.suspend();
      return;
    }
    if (!muted && !this.blocked && this.context?.state === 'suspended') {
      void this.context
        .resume()
        .then(() => {
          if (!this.context || this.muted || this.blocked) return;
          this.ensureBaseAmbience(this.context);
          if (this.desiredResultAmbience) this.startPersistentRarity(this.context, this.desiredResultAmbience);
        })
        .catch(() => undefined);
    }
  }

  public toggleMuted(): boolean {
    this.setMuted(!this.muted);
    return this.muted;
  }

  public setBlocked(blocked: boolean): void {
    this.blocked = blocked;
    if (blocked) this.stopDragTexture(true);
    if (blocked && this.context?.state === 'running') {
      void this.context.suspend();
      return;
    }
    if (!blocked && !this.muted && this.context?.state === 'suspended') {
      void this.context
        .resume()
        .then(() => {
          if (!this.context || this.muted || this.blocked) return;
          this.ensureBaseAmbience(this.context);
          if (this.desiredResultAmbience) this.startPersistentRarity(this.context, this.desiredResultAmbience);
        })
        .catch(() => undefined);
    }
  }

  public async preloadSamples(assets: readonly RuntimeSfxAsset[]): Promise<void> {
    if (assets.length === 0 || typeof AudioContext === 'undefined') return;
    const context = this.getContext();
    if (!context) return;

    await Promise.all(
      assets.map(async ({ cue, assetPath }) => {
        try {
          const response = await fetch(assetPath, { cache: 'force-cache' });
          if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
          }
          const encoded = await response.arrayBuffer();
          const decoded = await context.decodeAudioData(encoded);
          this.samples.set(cue, decoded);
        } catch (error: unknown) {
          console.warn(`[audio] failed to preload ${cue}; synth fallback remains active`, error);
        }
      }),
    );
  }

  public play(cue: SfxCue): void {
    if (this.muted || this.blocked || typeof AudioContext === 'undefined') return;

    const context = this.getContext();
    if (!context) return;

    if (context.state === 'suspended') {
      void context.resume().then(() => this.schedule(context, cue)).catch(() => undefined);
      return;
    }

    this.schedule(context, cue);
  }


  public playChipClack(progress: number): void {
    if (this.muted || this.blocked || typeof AudioContext === 'undefined') return;
    const context = this.getContext();
    if (!context) return;
    const schedule = (): void => {
      if (this.muted || this.blocked || context.state !== 'running') return;
      this.applyPresentationCue(context, 'chip-clack');
      this.scheduleChipClack(context, progress);
    };
    if (context.state === 'suspended') {
      void context.resume().then(schedule).catch(() => undefined);
      return;
    }
    schedule();
  }

  private getContext(): AudioContext | null {
    try {
      this.context ??= new AudioContext();
      return this.context;
    } catch {
      return null;
    }
  }

  private schedule(context: AudioContext, cue: SfxCue): void {
    if (this.muted || this.blocked || context.state !== 'running') return;

    this.applyPresentationCue(context, cue);
    const variation = getOneShotPitchVariation(cue);
    const pitchFactor = 1 + (Math.random() * 2 - 1) * variation;

    const sample = this.samples.get(cue);
    if (sample) {
      const source = context.createBufferSource();
      const gain = context.createGain();
      const start = context.currentTime;
      const playbackDuration = sample.duration / Math.max(0.5, pitchFactor);
      const tail = Math.min(0.12, Math.max(0.05, playbackDuration * 0.1));
      const fadeStart = start + Math.max(0, playbackDuration - tail);
      source.buffer = sample;
      source.playbackRate.setValueAtTime(pitchFactor, start);
      gain.gain.setValueAtTime(0.72, start);
      gain.gain.setValueAtTime(0.72, fadeStart);
      gain.gain.exponentialRampToValueAtTime(0.0001, start + playbackDuration);
      source.connect(gain);
      gain.connect(context.destination);
      source.start(start);
      return;
    }

    if (cue === 'chip-clack') {
      this.scheduleChipClack(context, 0.5);
      return;
    }
    if (cue === 'pouch-grab') {
      this.schedulePouchGrab(context, pitchFactor);
      return;
    }

    const now = context.currentTime;
    for (const spec of CUES[cue]) {
      const start = now + (spec.delay ?? 0);
      const end = start + spec.duration;
      const oscillator = context.createOscillator();
      const gain = context.createGain();
      oscillator.type = spec.type;
      oscillator.frequency.setValueAtTime(spec.frequency * pitchFactor, start);
      if (spec.endFrequency !== undefined) {
        oscillator.frequency.exponentialRampToValueAtTime(Math.max(1, spec.endFrequency * pitchFactor), end);
      }
      gain.gain.setValueAtTime(0.0001, start);
      gain.gain.exponentialRampToValueAtTime(spec.gain, start + Math.min(0.018, spec.duration / 4));
      gain.gain.exponentialRampToValueAtTime(0.0001, end);
      oscillator.connect(gain);
      gain.connect(context.destination);
      oscillator.start(start);
      oscillator.stop(end + 0.02);
    }
  }

  public setDragTexture(progress: number, velocity: number): void {
    if (this.muted || this.blocked || typeof AudioContext === 'undefined') {
      this.stopDragTexture(true);
      return;
    }

    const context = this.getContext();
    if (!context) return;
    if (context.state === 'suspended') {
      void context
        .resume()
        .then(() => {
          if (!this.muted && !this.blocked) this.updateDragTexture(context, progress, velocity);
        })
        .catch(() => undefined);
      return;
    }
    if (context.state === 'running') this.updateDragTexture(context, progress, velocity);
  }

  public stopDragTexture(immediate = false): void {
    this.cancelDragTextureIdleDecay();
    const source = this.dragTextureSource;
    const filter = this.dragTextureFilter;
    const gain = this.dragTextureGain;
    this.dragTextureSource = null;
    this.dragTextureFilter = null;
    this.dragTextureGain = null;
    this.dragTextureEnvelopeStartedAt = null;
    if (!source) return;

    const context = this.context;
    if (immediate || !context || context.state !== 'running' || !gain) {
      try {
        source.stop();
      } catch {
        // Already-stopped sources are harmless during rapid input teardown.
      }
      try { source.disconnect(); } catch { /* no-op */ }
      try { filter?.disconnect(); } catch { /* no-op */ }
      try { gain?.disconnect(); } catch { /* no-op */ }
      return;
    }

    const now = context.currentTime;
    const releaseSeconds = DRAG_TEXTURE_PROFILE.releaseMs / 1000;
    gain.gain.cancelScheduledValues(now);
    gain.gain.setValueAtTime(Math.max(0.0001, gain.gain.value), now);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + releaseSeconds);
    try {
      source.stop(now + releaseSeconds + 0.025);
    } catch {
      // Already-stopped sources are harmless during rapid input teardown.
    }
    window.setTimeout(() => {
      try { source.disconnect(); } catch { /* no-op */ }
      try { filter?.disconnect(); } catch { /* no-op */ }
      try { gain.disconnect(); } catch { /* no-op */ }
    }, DRAG_TEXTURE_PROFILE.releaseMs + 70);
  }

  private updateDragTexture(context: AudioContext, progress: number, velocity: number): void {
    const now = context.currentTime;
    const isStarting = !this.dragTextureSource || !this.dragTextureFilter || !this.dragTextureGain;
    if (isStarting || this.dragTextureEnvelopeStartedAt === null) this.dragTextureEnvelopeStartedAt = now;
    const startupProgress = Math.min(
      1,
      Math.max(0, ((now - this.dragTextureEnvelopeStartedAt) * 1000) / DRAG_TEXTURE_PROFILE.startAttackMs),
    );
    const mix = getDragTextureMix(progress, velocity, startupProgress);
    if (isStarting) {
      const source = context.createBufferSource();
      source.buffer = this.getAmbienceNoiseBuffer(context);
      source.loop = true;
      const filter = context.createBiquadFilter();
      filter.type = 'bandpass';
      filter.frequency.setValueAtTime(mix.bandHz, now);
      filter.Q.setValueAtTime(mix.q, now);
      const gain = context.createGain();
      gain.gain.setValueAtTime(0.0001, now);
      source.connect(filter);
      filter.connect(gain);
      gain.connect(context.destination);
      source.start(now, (now * 0.37) % 3.5);
      this.dragTextureSource = source;
      this.dragTextureFilter = filter;
      this.dragTextureGain = gain;
    }

    const filter = this.dragTextureFilter;
    const gain = this.dragTextureGain;
    if (!filter || !gain) return;
    const updateSeconds = DRAG_TEXTURE_PROFILE.updateMs / 1000;
    gain.gain.cancelScheduledValues(now);
    gain.gain.setValueAtTime(Math.max(0.0001, gain.gain.value), now);
    gain.gain.linearRampToValueAtTime(mix.gain, now + updateSeconds);
    filter.frequency.cancelScheduledValues(now);
    filter.frequency.setValueAtTime(Math.max(20, filter.frequency.value), now);
    filter.frequency.linearRampToValueAtTime(mix.bandHz, now + updateSeconds);
    filter.Q.cancelScheduledValues(now);
    filter.Q.setValueAtTime(Math.max(0.1, filter.Q.value), now);
    filter.Q.linearRampToValueAtTime(mix.q, now + updateSeconds);
    this.queueDragTextureIdleDecay();
  }

  private queueDragTextureIdleDecay(): void {
    this.cancelDragTextureIdleDecay();
    this.dragTextureIdleTimer = window.setTimeout(() => {
      this.dragTextureIdleTimer = null;
      this.silenceDragTexture();
    }, DRAG_TEXTURE_PROFILE.idleReleaseMs);
  }

  private cancelDragTextureIdleDecay(): void {
    if (this.dragTextureIdleTimer === null) return;
    window.clearTimeout(this.dragTextureIdleTimer);
    this.dragTextureIdleTimer = null;
  }

  private silenceDragTexture(): void {
    const context = this.context;
    const gain = this.dragTextureGain;
    if (!context || context.state !== 'running' || !gain) return;
    const now = context.currentTime;
    this.dragTextureEnvelopeStartedAt = null;
    gain.gain.cancelScheduledValues(now);
    gain.gain.setValueAtTime(Math.max(0.0001, gain.gain.value), now);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + DRAG_TEXTURE_PROFILE.releaseMs / 1000);
  }

  public beginRevealAnticipation(rarity: ResultAmbienceRarity, holdMs: number): void {
    const profile = getRevealAnticipationAudioProfile(rarity);
    if (!profile.enabled || holdMs <= 0 || this.muted || this.blocked || typeof AudioContext === 'undefined') return;

    const context = this.getContext();
    if (!context) return;
    const apply = (): void => {
      if (this.muted || this.blocked || context.state !== 'running') return;
      this.ensureBaseAmbience(context);
      this.desiredResultAmbience = null;
      this.cancelQueuedResultAmbience();
      const fadeOutMs = this.activeResultAmbience
        ? Math.min(120, getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs)
        : 70;
      this.stopPersistentRarity(context, fadeOutMs, false);
      this.duckBase(context, {
        multiplier: profile.multiplier,
        attackMs: profile.attackMs,
        holdMs,
        releaseMs: profile.releaseMs,
      });
    };

    if (context.state === 'running') {
      apply();
      return;
    }
    if (context.state === 'suspended') {
      void context.resume().then(apply).catch(() => undefined);
    }
  }

  public setResultAmbience(rarity: ResultAmbienceRarity): void {
    if (rarity === 'common') {
      this.clearResultAmbience();
      return;
    }
    this.desiredResultAmbience = rarity;
    this.cancelQueuedResultAmbience();
    const context = this.getContext();
    if (!context || this.muted || this.blocked) return;
    this.ensureBaseAmbience(context);
    if (context.state === 'running') {
      this.startPersistentRarity(context, rarity);
      return;
    }
    if (context.state === 'suspended') {
      void context
        .resume()
        .then(() => {
          if (!this.muted && !this.blocked && this.desiredResultAmbience === rarity) {
            this.startPersistentRarity(context, rarity);
          }
        })
        .catch(() => undefined);
    }
  }

  public clearResultAmbience(): void {
    this.desiredResultAmbience = null;
    this.cancelQueuedResultAmbience();
    if (this.context) {
      const fadeOutMs = this.activeResultAmbience
        ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
        : 190;
      this.stopPersistentRarity(this.context, fadeOutMs, true);
    }
  }

  public setResultBankingProgress(progress: number): void {
    const context = this.context;
    const rarity = this.activeResultAmbience;
    const bus = this.persistentRarityBus;
    if (!context || context.state !== 'running' || !rarity || !bus) return;

    const profile = getRarityAmbienceProfile(rarity);
    const clamped = Math.max(0, Math.min(1, progress));
    const eased = 1 - (1 - clamped) * (1 - clamped);
    const now = context.currentTime;
    const at = now + 0.07;
    const busTarget = profile.busGain * (1 + (profile.bankingPeakMultiplier - 1) * eased);
    bus.gain.cancelScheduledValues(now);
    bus.gain.setValueAtTime(Math.max(0.0001, bus.gain.value), now);
    bus.gain.linearRampToValueAtTime(busTarget, at);

    const toneFilter = this.persistentRarityToneFilter;
    if (toneFilter) {
      toneFilter.frequency.cancelScheduledValues(now);
      toneFilter.frequency.setValueAtTime(Math.max(20, toneFilter.frequency.value), now);
      toneFilter.frequency.linearRampToValueAtTime(
        profile.toneLowpassHz + profile.bankingToneFilterLiftHz * eased,
        at,
      );
    }

    const shimmerGain = this.persistentRarityShimmerGain;
    if (shimmerGain) {
      shimmerGain.gain.cancelScheduledValues(now);
      shimmerGain.gain.setValueAtTime(Math.max(0.0001, shimmerGain.gain.value), now);
      shimmerGain.gain.linearRampToValueAtTime(
        profile.shimmerGain * (1 + (profile.bankingShimmerMultiplier - 1) * eased),
        at,
      );
    }
  }

  private applyPresentationCue(context: AudioContext, cue: SfxCue): void {
    this.ensureBaseAmbience(context);
    const directive = getAudioCuePresentationDirective(cue);
    if (directive.clearPersistent) {
      this.desiredResultAmbience = null;
      this.cancelQueuedResultAmbience();
      const fadeOutMs = this.activeResultAmbience
        ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
        : 140;
      this.stopPersistentRarity(context, fadeOutMs, true);
    }
    if (directive.duck) this.duckBase(context, directive.duck);
    if (directive.persistent) {
      this.queuePersistentRarity(context, directive.persistent, directive.persistentDelayMs ?? 0);
    }
  }

  private ensureBaseAmbience(context: AudioContext): void {
    if (this.baseAmbienceBus) return;
    const now = context.currentTime;
    const bus = context.createGain();
    bus.gain.setValueAtTime(0.0001, now);
    bus.gain.linearRampToValueAtTime(
      BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier,
      now + BASE_AMBIENCE_PROFILE.fadeInMs / 1000,
    );
    bus.connect(context.destination);
    this.baseAmbienceBus = bus;

    const room = context.createBufferSource();
    room.buffer = this.getAmbienceNoiseBuffer(context);
    room.loop = true;
    const roomLow = context.createBiquadFilter();
    roomLow.type = 'lowpass';
    roomLow.frequency.setValueAtTime(BASE_AMBIENCE_PROFILE.roomLowpassHz, now);
    roomLow.Q.setValueAtTime(0.38, now);
    const roomHigh = context.createBiquadFilter();
    roomHigh.type = 'highpass';
    roomHigh.frequency.setValueAtTime(BASE_AMBIENCE_PROFILE.roomHighpassHz, now);
    const roomGain = context.createGain();
    roomGain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.roomNoiseGain, now);
    room.connect(roomLow);
    roomLow.connect(roomHigh);
    roomHigh.connect(roomGain);
    roomGain.connect(bus);
    room.start(now);

    // The original 55/110 Hz transformer layer read as a server-room fan in
    // headphones. Keep the profile field for tuneability, but do not construct
    // a machine-hum layer when the reviewed profile disables it.
    if (BASE_AMBIENCE_PROFILE.humGain > 0) {
      const hum = context.createOscillator();
      const humGain = context.createGain();
      hum.type = 'sine';
      hum.frequency.setValueAtTime(146.83, now);
      humGain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.humGain, now);
      hum.connect(humGain);
      humGain.connect(bus);
      hum.start(now);
    }

    const padFilter = context.createBiquadFilter();
    padFilter.type = 'lowpass';
    padFilter.frequency.setValueAtTime(BASE_AMBIENCE_PROFILE.padLowpassHz, now);
    padFilter.Q.setValueAtTime(0.32, now);
    padFilter.connect(bus);
    BASE_AMBIENCE_PROFILE.padFrequencies.forEach((frequency, index) => {
      const oscillator = context.createOscillator();
      const gain = context.createGain();
      oscillator.type = 'sine';
      oscillator.frequency.setValueAtTime(frequency, now);
      oscillator.detune.setValueAtTime(index === 0 ? -2 : index === 1 ? 1.5 : 3, now);
      gain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.padGain / BASE_AMBIENCE_PROFILE.padFrequencies.length, now);
      oscillator.connect(gain);
      gain.connect(padFilter);
      oscillator.start(now);
    });
    const padLfo = context.createOscillator();
    const padLfoDepth = context.createGain();
    padLfo.type = 'sine';
    padLfo.frequency.setValueAtTime(BASE_AMBIENCE_PROFILE.padMotionRateHz, now);
    padLfoDepth.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.padFilterSweepHz, now);
    padLfo.connect(padLfoDepth);
    padLfoDepth.connect(padFilter.frequency);
    padLfo.start(now);

    const shimmer = context.createBufferSource();
    shimmer.buffer = this.getAmbienceNoiseBuffer(context);
    shimmer.loop = true;
    const shimmerHigh = context.createBiquadFilter();
    shimmerHigh.type = 'highpass';
    shimmerHigh.frequency.setValueAtTime(3000, now);
    const shimmerLow = context.createBiquadFilter();
    shimmerLow.type = 'lowpass';
    shimmerLow.frequency.setValueAtTime(6800, now);
    const shimmerGain = context.createGain();
    shimmerGain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.shimmerGain, now);
    shimmer.connect(shimmerHigh);
    shimmerHigh.connect(shimmerLow);
    shimmerLow.connect(shimmerGain);
    shimmerGain.connect(bus);
    shimmer.start(now + 0.37);

    const shimmerLfo = context.createOscillator();
    const shimmerLfoDepth = context.createGain();
    shimmerLfo.type = 'sine';
    shimmerLfo.frequency.setValueAtTime(BASE_AMBIENCE_PROFILE.shimmerMotionRateHz, now);
    shimmerLfoDepth.gain.setValueAtTime(
      BASE_AMBIENCE_PROFILE.shimmerGain * BASE_AMBIENCE_PROFILE.shimmerMotionDepth,
      now,
    );
    shimmerLfo.connect(shimmerLfoDepth);
    shimmerLfoDepth.connect(shimmerGain.gain);
    shimmerLfo.start(now + 0.53);
  }

  private duckBase(
    context: AudioContext,
    duck: { multiplier: number; attackMs: number; holdMs: number; releaseMs: number },
  ): void {
    this.ensureBaseAmbience(context);
    if (!this.baseAmbienceBus) return;
    const now = context.currentTime;
    const gain = this.baseAmbienceBus.gain;
    const steady = BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier;
    const ducked = Math.max(0.0001, steady * duck.multiplier);
    gain.cancelScheduledValues(now);
    gain.setValueAtTime(Math.max(0.0001, gain.value), now);
    gain.linearRampToValueAtTime(ducked, now + duck.attackMs / 1000);
    gain.setValueAtTime(ducked, now + (duck.attackMs + duck.holdMs) / 1000);
    gain.linearRampToValueAtTime(steady, now + (duck.attackMs + duck.holdMs + duck.releaseMs) / 1000);
  }

  private setSteadyBaseMultiplier(context: AudioContext, multiplier: number, rampMs = 220): void {
    this.steadyBaseMultiplier = multiplier;
    this.ensureBaseAmbience(context);
    if (!this.baseAmbienceBus) return;
    const now = context.currentTime;
    const gain = this.baseAmbienceBus.gain;
    gain.cancelScheduledValues(now);
    gain.setValueAtTime(Math.max(0.0001, gain.value), now);
    gain.linearRampToValueAtTime(
      BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier,
      now + rampMs / 1000,
    );
  }

  private queuePersistentRarity(
    context: AudioContext,
    rarity: PersistentResultAmbience,
    delayMs: number,
  ): void {
    this.desiredResultAmbience = rarity;
    this.cancelQueuedResultAmbience();
    const fadeOutMs = this.activeResultAmbience
      ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
      : 120;
    this.stopPersistentRarity(context, fadeOutMs, false);
    this.resultAmbienceTimer = window.setTimeout(() => {
      this.resultAmbienceTimer = null;
      if (this.muted || this.blocked || this.desiredResultAmbience !== rarity) return;
      if (context.state === 'running') this.startPersistentRarity(context, rarity);
    }, delayMs);
  }

  private cancelQueuedResultAmbience(): void {
    if (this.resultAmbienceTimer === null) return;
    window.clearTimeout(this.resultAmbienceTimer);
    this.resultAmbienceTimer = null;
  }

  private startPersistentRarity(context: AudioContext, rarity: PersistentResultAmbience): void {
    if (this.muted || this.blocked || context.state !== 'running') return;
    if (this.activeResultAmbience === rarity && this.persistentRarityBus) return;
    const profile = getRarityAmbienceProfile(rarity);
    if (!profile.enabled) return;

    const previousFadeOutMs = this.activeResultAmbience
      ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
      : 140;
    this.stopPersistentRarity(context, previousFadeOutMs, false);
    this.activeResultAmbience = rarity;
    this.desiredResultAmbience = rarity;
    this.setSteadyBaseMultiplier(context, profile.baseMixMultiplier, profile.fadeInMs);

    const now = context.currentTime;
    const bus = context.createGain();
    const introPeakAt = now + profile.introPeakMs / 1000;
    const introSettleAt = introPeakAt + profile.introSettleMs / 1000;
    bus.gain.setValueAtTime(0.0001, now);
    bus.gain.linearRampToValueAtTime(profile.busGain * profile.introPeakMultiplier, introPeakAt);
    bus.gain.linearRampToValueAtTime(profile.busGain, introSettleAt);
    bus.connect(context.destination);
    this.persistentRarityBus = bus;

    const toneFilter = context.createBiquadFilter();
    toneFilter.type = 'lowpass';
    toneFilter.frequency.setValueAtTime(profile.toneLowpassHz, now);
    toneFilter.Q.setValueAtTime(0.65, now);
    this.persistentRarityToneFilter = toneFilter;
    const toneGain = context.createGain();
    toneGain.gain.setValueAtTime(profile.toneGain / Math.max(1, profile.toneFrequencies.length), now);
    toneGain.connect(toneFilter);
    toneFilter.connect(bus);

    profile.toneFrequencies.forEach((frequency, index) => {
      const oscillator = context.createOscillator();
      const panner = context.createStereoPanner();
      oscillator.type = 'sine';
      oscillator.frequency.setValueAtTime(frequency, now);
      oscillator.detune.setValueAtTime((index - (profile.toneFrequencies.length - 1) / 2) * 1.6, now);
      const side = index % 2 === 0 ? -1 : 1;
      panner.pan.setValueAtTime(side * profile.stereoSpread * Math.min(1, 0.45 + index * 0.12), now);
      oscillator.connect(panner);
      panner.connect(toneGain);
      oscillator.start(now);
      this.persistentRaritySources.push(oscillator);
    });

    const pulse = context.createOscillator();
    const pulseDepth = context.createGain();
    pulse.type = 'sine';
    pulse.frequency.setValueAtTime(profile.pulseRateHz, now);
    pulseDepth.gain.setValueAtTime(
      (profile.toneGain / Math.max(1, profile.toneFrequencies.length)) * profile.pulseDepth,
      now,
    );
    pulse.connect(pulseDepth);
    pulseDepth.connect(toneGain.gain);
    pulse.start(now);
    this.persistentRaritySources.push(pulse);

    // One slow shared colour source changes spectral balance without creating a melody.
    const colour = context.createOscillator();
    const toneColourDepth = context.createGain();
    colour.type = 'sine';
    colour.frequency.setValueAtTime(profile.motionRateHz, now);
    toneColourDepth.gain.setValueAtTime(profile.toneFilterMotionHz, now);
    colour.connect(toneColourDepth);
    toneColourDepth.connect(toneFilter.frequency);
    colour.start(now + 0.17);
    this.persistentRaritySources.push(colour);

    if (profile.shimmerGain > 0) {
      const shimmer = context.createBufferSource();
      shimmer.buffer = this.getAmbienceNoiseBuffer(context);
      shimmer.loop = true;
      const shimmerBand = context.createBiquadFilter();
      shimmerBand.type = 'bandpass';
      shimmerBand.frequency.setValueAtTime(profile.shimmerBandHz, now);
      shimmerBand.Q.setValueAtTime(rarity === 'secret' ? 0.62 : 0.78, now);
      const shimmerGain = context.createGain();
      shimmerGain.gain.setValueAtTime(profile.shimmerGain, now);
      this.persistentRarityShimmerGain = shimmerGain;
      const shimmerBandDepth = context.createGain();
      shimmerBandDepth.gain.setValueAtTime(profile.shimmerBandMotionHz, now);
      const shimmerGainDepth = context.createGain();
      shimmerGainDepth.gain.setValueAtTime(profile.shimmerGain * profile.shimmerMotionDepth, now);
      colour.connect(shimmerBandDepth);
      shimmerBandDepth.connect(shimmerBand.frequency);
      colour.connect(shimmerGainDepth);
      shimmerGainDepth.connect(shimmerGain.gain);
      shimmer.connect(shimmerBand);
      shimmerBand.connect(shimmerGain);
      shimmerGain.connect(bus);
      shimmer.start(now + 0.11);
      this.persistentRaritySources.push(shimmer);
    }
  }

  private stopPersistentRarity(context: AudioContext, fadeMs: number, restoreBase: boolean): void {
    const bus = this.persistentRarityBus;
    const sources = this.persistentRaritySources;
    this.persistentRarityBus = null;
    this.persistentRarityToneFilter = null;
    this.persistentRarityShimmerGain = null;
    this.persistentRaritySources = [];
    this.activeResultAmbience = null;
    if (bus) {
      const now = context.currentTime;
      bus.gain.cancelScheduledValues(now);
      bus.gain.setValueAtTime(Math.max(0.0001, bus.gain.value), now);
      bus.gain.exponentialRampToValueAtTime(0.0001, now + Math.max(0.03, fadeMs / 1000));
      for (const source of sources) {
        try {
          source.stop(now + Math.max(0.05, fadeMs / 1000 + 0.03));
        } catch {
          // Already-stopped sources are harmless during teardown/re-entry.
        }
      }
      window.setTimeout(() => {
        try {
          bus.disconnect();
        } catch {
          // The old local bus may already be disconnected during rapid re-entry.
        }
      }, fadeMs + 80);
    }
    if (restoreBase) this.setSteadyBaseMultiplier(context, 1, Math.max(180, fadeMs));
  }

  private getAmbienceNoiseBuffer(context: AudioContext): AudioBuffer {
    if (this.ambienceNoiseBuffer && this.ambienceNoiseBuffer.sampleRate === context.sampleRate) {
      return this.ambienceNoiseBuffer;
    }

    const seconds = 4;
    const length = Math.max(1, Math.floor(context.sampleRate * seconds));
    const buffer = context.createBuffer(1, length, context.sampleRate);
    const channel = buffer.getChannelData(0);
    let seed = 0x0a11d10f;
    for (let index = 0; index < channel.length; index += 1) {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      channel[index] = (seed / 0xffffffff) * 2 - 1;
    }
    const fadeLength = Math.min(Math.floor(context.sampleRate * 0.12), Math.floor(channel.length / 8));
    for (let index = 0; index < fadeLength; index += 1) {
      const mix = index / Math.max(1, fadeLength - 1);
      const tailIndex = channel.length - fadeLength + index;
      channel[tailIndex] = (channel[tailIndex] ?? 0) * (1 - mix) + (channel[index] ?? 0) * mix;
    }
    this.ambienceNoiseBuffer = buffer;
    return buffer;
  }

  private schedulePouchGrab(context: AudioContext, pitchFactor: number): void {
    const now = context.currentTime;
    const noise = context.createBufferSource();
    noise.buffer = this.getChipNoiseBuffer(context);
    const band = context.createBiquadFilter();
    band.type = 'bandpass';
    band.frequency.setValueAtTime(3300 * pitchFactor, now);
    band.Q.setValueAtTime(1.35, now);
    const noiseGain = context.createGain();
    noiseGain.gain.setValueAtTime(0.0001, now);
    noiseGain.gain.exponentialRampToValueAtTime(0.043, now + 0.001);
    noiseGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.027);
    noise.connect(band);
    band.connect(noiseGain);
    noiseGain.connect(context.destination);
    noise.start(now);
    noise.stop(now + 0.032);

    const body = context.createOscillator();
    const bodyGain = context.createGain();
    body.type = 'triangle';
    body.frequency.setValueAtTime(430 * pitchFactor, now + 0.004);
    body.frequency.exponentialRampToValueAtTime(255 * pitchFactor, now + 0.052);
    bodyGain.gain.setValueAtTime(0.0001, now);
    bodyGain.gain.exponentialRampToValueAtTime(0.028, now + 0.005);
    bodyGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.055);
    body.connect(bodyGain);
    bodyGain.connect(context.destination);
    body.start(now + 0.004);
    body.stop(now + 0.06);
  }

  private scheduleChipClack(context: AudioContext, progress: number): void {
    const now = context.currentTime;
    const variant = getChipPitchMultiplier(progress, Math.random());

    const noise = context.createBufferSource();
    noise.buffer = this.getChipNoiseBuffer(context);
    const band = context.createBiquadFilter();
    band.type = 'bandpass';
    band.frequency.setValueAtTime(2350 * variant, now);
    band.Q.setValueAtTime(1.9, now);
    const noiseGain = context.createGain();
    noiseGain.gain.setValueAtTime(0.0001, now);
    noiseGain.gain.exponentialRampToValueAtTime(0.075, now + 0.0015);
    noiseGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.03);
    noise.connect(band);
    band.connect(noiseGain);
    noiseGain.connect(context.destination);
    noise.start(now);
    noise.stop(now + 0.036);

    const body = context.createOscillator();
    const bodyGain = context.createGain();
    body.type = 'triangle';
    body.frequency.setValueAtTime(1180 * variant, now);
    body.frequency.exponentialRampToValueAtTime(860 * variant, now + 0.024);
    bodyGain.gain.setValueAtTime(0.0001, now);
    bodyGain.gain.exponentialRampToValueAtTime(0.038, now + 0.001);
    bodyGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.026);
    body.connect(bodyGain);
    bodyGain.connect(context.destination);
    body.start(now);
    body.stop(now + 0.03);
  }

  private getChipNoiseBuffer(context: AudioContext): AudioBuffer {
    if (this.chipNoiseBuffer && this.chipNoiseBuffer.sampleRate === context.sampleRate) {
      return this.chipNoiseBuffer;
    }

    const length = Math.max(1, Math.floor(context.sampleRate * 0.04));
    const buffer = context.createBuffer(1, length, context.sampleRate);
    const channel = buffer.getChannelData(0);
    let seed = 0x5eed1234;
    for (let index = 0; index < channel.length; index += 1) {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      channel[index] = ((seed / 0xffffffff) * 2 - 1) * (1 - index / channel.length);
    }
    this.chipNoiseBuffer = buffer;
    return buffer;
  }
}

const gameAudio = new GameAudioController();

export const getGameAudio = (): GameAudioController => gameAudio;
