import type { RuntimeSfxAsset, SfxCue } from '../data/audioAssets';
import {
  BASE_AMBIENCE_PROFILE,
  getAudioCuePresentationDirective,
  getRarityAmbienceProfile,
  type PersistentResultAmbience,
  type ResultAmbienceRarity,
} from '../data/audioPresentation';

export type { SfxCue } from '../data/audioAssets';

interface ToneSpec {
  frequency: number;
  endFrequency?: number;
  duration: number;
  type: OscillatorType;
  gain: number;
  delay?: number;
}

const CUES: Readonly<Record<SfxCue, readonly ToneSpec[]>> = {
  tear: [
    { frequency: 260, endFrequency: 105, duration: 0.1, type: 'sawtooth', gain: 0.035 },
    { frequency: 690, endFrequency: 330, duration: 0.07, type: 'square', gain: 0.018, delay: 0.045 },
  ],
  'reveal-pop': [{ frequency: 180, endFrequency: 520, duration: 0.11, type: 'sine', gain: 0.055 }],
  common: [{ frequency: 520, duration: 0.12, type: 'sine', gain: 0.035 }],
  rare: [
    { frequency: 560, duration: 0.12, type: 'sine', gain: 0.036 },
    { frequency: 720, duration: 0.14, type: 'sine', gain: 0.03, delay: 0.07 },
  ],
  epic: [
    { frequency: 610, duration: 0.13, type: 'triangle', gain: 0.038 },
    { frequency: 820, duration: 0.15, type: 'sine', gain: 0.032, delay: 0.07 },
    { frequency: 1040, duration: 0.17, type: 'sine', gain: 0.026, delay: 0.14 },
  ],
  legendary: [
    { frequency: 650, duration: 0.16, type: 'triangle', gain: 0.04 },
    { frequency: 880, duration: 0.18, type: 'sine', gain: 0.035, delay: 0.08 },
    { frequency: 1180, duration: 0.22, type: 'sine', gain: 0.03, delay: 0.16 },
  ],
  duplicate: [{ frequency: 230, endFrequency: 180, duration: 0.11, type: 'triangle', gain: 0.026 }],
  'ui-click': [
    { frequency: 880, endFrequency: 690, duration: 0.038, type: 'square', gain: 0.022 },
    { frequency: 1280, duration: 0.026, type: 'triangle', gain: 0.012, delay: 0.012 },
  ],
  'ui-skip': [
    { frequency: 1480, endFrequency: 920, duration: 0.042, type: 'square', gain: 0.026 },
    { frequency: 1840, duration: 0.026, type: 'triangle', gain: 0.015, delay: 0.018 },
  ],
  'pouch-select': [
    { frequency: 520, endFrequency: 720, duration: 0.055, type: 'triangle', gain: 0.026 },
    { frequency: 920, endFrequency: 1080, duration: 0.045, type: 'sine', gain: 0.018, delay: 0.035 },
  ],
  // `pouch-grab` is generated by schedulePouchGrab for a short plastic zip/pop transient.
  'pouch-grab': [],
  'ui-denied': [
    { frequency: 250, endFrequency: 185, duration: 0.055, type: 'square', gain: 0.025 },
    { frequency: 190, endFrequency: 150, duration: 0.05, type: 'triangle', gain: 0.02, delay: 0.045 },
  ],
  'charged-spend': [
    { frequency: 980, endFrequency: 430, duration: 0.085, type: 'square', gain: 0.024 },
    { frequency: 360, endFrequency: 250, duration: 0.09, type: 'triangle', gain: 0.022, delay: 0.025 },
  ],
  // `chip-clack` is generated by scheduleChipClack so it can sound percussive
  // without requiring an unreviewed binary sample.
  'chip-clack': [],
  'signal-gain': [{ frequency: 780, endFrequency: 920, duration: 0.09, type: 'square', gain: 0.018 }],
  'signal-lock': [
    { frequency: 450, endFrequency: 900, duration: 0.18, type: 'square', gain: 0.025 },
    { frequency: 1120, duration: 0.16, type: 'sine', gain: 0.028, delay: 0.14 },
  ],
  'hidden-pocket': [
    { frequency: 350, endFrequency: 760, duration: 0.15, type: 'triangle', gain: 0.035 },
    { frequency: 980, endFrequency: 620, duration: 0.2, type: 'sine', gain: 0.025, delay: 0.11 },
  ],
  'secret-reveal': [
    { frequency: 720, duration: 0.18, type: 'triangle', gain: 0.04 },
    { frequency: 1080, duration: 0.24, type: 'sine', gain: 0.035, delay: 0.09 },
    { frequency: 1440, duration: 0.28, type: 'sine', gain: 0.028, delay: 0.18 },
  ],
  'collection-complete': [
    { frequency: 523, duration: 0.13, type: 'sine', gain: 0.032 },
    { frequency: 659, duration: 0.13, type: 'sine', gain: 0.032, delay: 0.09 },
    { frequency: 784, duration: 0.2, type: 'sine', gain: 0.032, delay: 0.18 },
  ],
};

class GameAudioController {
  private context: AudioContext | null = null;
  private readonly samples = new Map<SfxCue, AudioBuffer>();
  private chipNoiseBuffer: AudioBuffer | null = null;
  private ambienceNoiseBuffer: AudioBuffer | null = null;
  private baseAmbienceBus: GainNode | null = null;
  private persistentRarityBus: GainNode | null = null;
  private persistentRaritySources: AudioScheduledSourceNode[] = [];
  private activeResultAmbience: PersistentResultAmbience | null = null;
  private desiredResultAmbience: PersistentResultAmbience | null = null;
  private resultAmbienceTimer: number | null = null;
  private steadyBaseMultiplier = 1;
  private chipClackIndex = 0;
  private muted = false;
  private blocked = false;

  public isMuted(): boolean {
    return this.muted;
  }

  public setMuted(muted: boolean): void {
    this.muted = muted;
    if (muted && this.context?.state === 'running') {
      void this.context.suspend();
      return;
    }
    if (!muted && !this.blocked && this.context?.state === 'suspended') {
      void this.context
        .resume()
        .then(() => {
          if (!this.context || this.muted || this.blocked) return;
          this.ensureBaseAmbience(this.context);
          if (this.desiredResultAmbience) this.startPersistentRarity(this.context, this.desiredResultAmbience);
        })
        .catch(() => undefined);
    }
  }

  public toggleMuted(): boolean {
    this.setMuted(!this.muted);
    return this.muted;
  }

  public setBlocked(blocked: boolean): void {
    this.blocked = blocked;
    if (blocked && this.context?.state === 'running') {
      void this.context.suspend();
      return;
    }
    if (!blocked && !this.muted && this.context?.state === 'suspended') {
      void this.context
        .resume()
        .then(() => {
          if (!this.context || this.muted || this.blocked) return;
          this.ensureBaseAmbience(this.context);
          if (this.desiredResultAmbience) this.startPersistentRarity(this.context, this.desiredResultAmbience);
        })
        .catch(() => undefined);
    }
  }

  public async preloadSamples(assets: readonly RuntimeSfxAsset[]): Promise<void> {
    if (assets.length === 0 || typeof AudioContext === 'undefined') return;
    const context = this.getContext();
    if (!context) return;

    await Promise.all(
      assets.map(async ({ cue, assetPath }) => {
        try {
          const response = await fetch(assetPath, { cache: 'force-cache' });
          if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
          }
          const encoded = await response.arrayBuffer();
          const decoded = await context.decodeAudioData(encoded);
          this.samples.set(cue, decoded);
        } catch (error: unknown) {
          console.warn(`[audio] failed to preload ${cue}; synth fallback remains active`, error);
        }
      }),
    );
  }

  public play(cue: SfxCue): void {
    if (this.muted || this.blocked || typeof AudioContext === 'undefined') return;

    const context = this.getContext();
    if (!context) return;

    if (context.state === 'suspended') {
      void context.resume().then(() => this.schedule(context, cue)).catch(() => undefined);
      return;
    }

    this.schedule(context, cue);
  }

  private getContext(): AudioContext | null {
    try {
      this.context ??= new AudioContext();
      return this.context;
    } catch {
      return null;
    }
  }

  private schedule(context: AudioContext, cue: SfxCue): void {
    if (this.muted || this.blocked || context.state !== 'running') return;

    this.applyPresentationCue(context, cue);

    const sample = this.samples.get(cue);
    if (sample) {
      const source = context.createBufferSource();
      const gain = context.createGain();
      const start = context.currentTime;
      const tail = Math.min(0.12, Math.max(0.05, sample.duration * 0.1));
      const fadeStart = start + Math.max(0, sample.duration - tail);
      source.buffer = sample;
      gain.gain.setValueAtTime(0.72, start);
      gain.gain.setValueAtTime(0.72, fadeStart);
      gain.gain.exponentialRampToValueAtTime(0.0001, start + sample.duration);
      source.connect(gain);
      gain.connect(context.destination);
      source.start(start);
      return;
    }

    if (cue === 'chip-clack') {
      this.scheduleChipClack(context);
      return;
    }
    if (cue === 'pouch-grab') {
      this.schedulePouchGrab(context);
      return;
    }

    const now = context.currentTime;
    for (const spec of CUES[cue]) {
      const start = now + (spec.delay ?? 0);
      const end = start + spec.duration;
      const oscillator = context.createOscillator();
      const gain = context.createGain();
      oscillator.type = spec.type;
      oscillator.frequency.setValueAtTime(spec.frequency, start);
      if (spec.endFrequency !== undefined) {
        oscillator.frequency.exponentialRampToValueAtTime(Math.max(1, spec.endFrequency), end);
      }
      gain.gain.setValueAtTime(0.0001, start);
      gain.gain.exponentialRampToValueAtTime(spec.gain, start + Math.min(0.018, spec.duration / 4));
      gain.gain.exponentialRampToValueAtTime(0.0001, end);
      oscillator.connect(gain);
      gain.connect(context.destination);
      oscillator.start(start);
      oscillator.stop(end + 0.02);
    }
  }

  public setResultAmbience(rarity: ResultAmbienceRarity): void {
    if (rarity === 'common') {
      this.clearResultAmbience();
      return;
    }
    this.desiredResultAmbience = rarity;
    this.cancelQueuedResultAmbience();
    const context = this.getContext();
    if (!context || this.muted || this.blocked) return;
    this.ensureBaseAmbience(context);
    if (context.state === 'running') {
      this.startPersistentRarity(context, rarity);
      return;
    }
    if (context.state === 'suspended') {
      void context
        .resume()
        .then(() => {
          if (!this.muted && !this.blocked && this.desiredResultAmbience === rarity) {
            this.startPersistentRarity(context, rarity);
          }
        })
        .catch(() => undefined);
    }
  }

  public clearResultAmbience(): void {
    this.desiredResultAmbience = null;
    this.cancelQueuedResultAmbience();
    if (this.context) {
      const fadeOutMs = this.activeResultAmbience
        ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
        : 190;
      this.stopPersistentRarity(this.context, fadeOutMs, true);
    }
  }

  private applyPresentationCue(context: AudioContext, cue: SfxCue): void {
    this.ensureBaseAmbience(context);
    const directive = getAudioCuePresentationDirective(cue);
    if (directive.clearPersistent) {
      this.desiredResultAmbience = null;
      this.cancelQueuedResultAmbience();
      const fadeOutMs = this.activeResultAmbience
        ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
        : 140;
      this.stopPersistentRarity(context, fadeOutMs, true);
    }
    if (directive.duck) this.duckBase(context, directive.duck);
    if (directive.persistent) {
      this.queuePersistentRarity(context, directive.persistent, directive.persistentDelayMs ?? 0);
    }
  }

  private ensureBaseAmbience(context: AudioContext): void {
    if (this.baseAmbienceBus) return;
    const now = context.currentTime;
    const bus = context.createGain();
    bus.gain.setValueAtTime(0.0001, now);
    bus.gain.linearRampToValueAtTime(
      BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier,
      now + BASE_AMBIENCE_PROFILE.fadeInMs / 1000,
    );
    bus.connect(context.destination);
    this.baseAmbienceBus = bus;

    const room = context.createBufferSource();
    room.buffer = this.getAmbienceNoiseBuffer(context);
    room.loop = true;
    const roomLow = context.createBiquadFilter();
    roomLow.type = 'lowpass';
    roomLow.frequency.setValueAtTime(1450, now);
    roomLow.Q.setValueAtTime(0.55, now);
    const roomHigh = context.createBiquadFilter();
    roomHigh.type = 'highpass';
    roomHigh.frequency.setValueAtTime(38, now);
    const roomGain = context.createGain();
    roomGain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.roomNoiseGain, now);
    room.connect(roomLow);
    roomLow.connect(roomHigh);
    roomHigh.connect(roomGain);
    roomGain.connect(bus);
    room.start(now);

    const humFilter = context.createBiquadFilter();
    humFilter.type = 'lowpass';
    humFilter.frequency.setValueAtTime(230, now);
    humFilter.Q.setValueAtTime(0.7, now);
    humFilter.connect(bus);
    const humFrequencies = [55, 110] as const;
    humFrequencies.forEach((frequency, index) => {
      const oscillator = context.createOscillator();
      const gain = context.createGain();
      oscillator.type = index === 0 ? 'sine' : 'triangle';
      oscillator.frequency.setValueAtTime(frequency, now);
      gain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.humGain / humFrequencies.length, now);
      oscillator.connect(gain);
      gain.connect(humFilter);
      oscillator.start(now);
    });

    const padFilter = context.createBiquadFilter();
    padFilter.type = 'lowpass';
    padFilter.frequency.setValueAtTime(620, now);
    padFilter.Q.setValueAtTime(0.42, now);
    padFilter.connect(bus);
    BASE_AMBIENCE_PROFILE.padFrequencies.forEach((frequency, index) => {
      const oscillator = context.createOscillator();
      const gain = context.createGain();
      oscillator.type = index === 1 ? 'sine' : 'triangle';
      oscillator.frequency.setValueAtTime(frequency, now);
      oscillator.detune.setValueAtTime(index === 0 ? -4 : index === 1 ? 3 : 0, now);
      gain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.padGain / BASE_AMBIENCE_PROFILE.padFrequencies.length, now);
      oscillator.connect(gain);
      gain.connect(padFilter);
      oscillator.start(now);
    });
    const padLfo = context.createOscillator();
    const padLfoDepth = context.createGain();
    padLfo.type = 'sine';
    padLfo.frequency.setValueAtTime(0.028, now);
    padLfoDepth.gain.setValueAtTime(95, now);
    padLfo.connect(padLfoDepth);
    padLfoDepth.connect(padFilter.frequency);
    padLfo.start(now);

    const shimmer = context.createBufferSource();
    shimmer.buffer = this.getAmbienceNoiseBuffer(context);
    shimmer.loop = true;
    const shimmerHigh = context.createBiquadFilter();
    shimmerHigh.type = 'highpass';
    shimmerHigh.frequency.setValueAtTime(3000, now);
    const shimmerLow = context.createBiquadFilter();
    shimmerLow.type = 'lowpass';
    shimmerLow.frequency.setValueAtTime(6800, now);
    const shimmerGain = context.createGain();
    shimmerGain.gain.setValueAtTime(BASE_AMBIENCE_PROFILE.shimmerGain, now);
    shimmer.connect(shimmerHigh);
    shimmerHigh.connect(shimmerLow);
    shimmerLow.connect(shimmerGain);
    shimmerGain.connect(bus);
    shimmer.start(now + 0.37);
  }

  private duckBase(
    context: AudioContext,
    duck: { multiplier: number; attackMs: number; holdMs: number; releaseMs: number },
  ): void {
    this.ensureBaseAmbience(context);
    if (!this.baseAmbienceBus) return;
    const now = context.currentTime;
    const gain = this.baseAmbienceBus.gain;
    const steady = BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier;
    const ducked = Math.max(0.0001, steady * duck.multiplier);
    gain.cancelScheduledValues(now);
    gain.setValueAtTime(Math.max(0.0001, gain.value), now);
    gain.linearRampToValueAtTime(ducked, now + duck.attackMs / 1000);
    gain.setValueAtTime(ducked, now + (duck.attackMs + duck.holdMs) / 1000);
    gain.linearRampToValueAtTime(steady, now + (duck.attackMs + duck.holdMs + duck.releaseMs) / 1000);
  }

  private setSteadyBaseMultiplier(context: AudioContext, multiplier: number, rampMs = 220): void {
    this.steadyBaseMultiplier = multiplier;
    this.ensureBaseAmbience(context);
    if (!this.baseAmbienceBus) return;
    const now = context.currentTime;
    const gain = this.baseAmbienceBus.gain;
    gain.cancelScheduledValues(now);
    gain.setValueAtTime(Math.max(0.0001, gain.value), now);
    gain.linearRampToValueAtTime(
      BASE_AMBIENCE_PROFILE.busGain * this.steadyBaseMultiplier,
      now + rampMs / 1000,
    );
  }

  private queuePersistentRarity(
    context: AudioContext,
    rarity: PersistentResultAmbience,
    delayMs: number,
  ): void {
    this.desiredResultAmbience = rarity;
    this.cancelQueuedResultAmbience();
    const fadeOutMs = this.activeResultAmbience
      ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
      : 120;
    this.stopPersistentRarity(context, fadeOutMs, false);
    this.resultAmbienceTimer = window.setTimeout(() => {
      this.resultAmbienceTimer = null;
      if (this.muted || this.blocked || this.desiredResultAmbience !== rarity) return;
      if (context.state === 'running') this.startPersistentRarity(context, rarity);
    }, delayMs);
  }

  private cancelQueuedResultAmbience(): void {
    if (this.resultAmbienceTimer === null) return;
    window.clearTimeout(this.resultAmbienceTimer);
    this.resultAmbienceTimer = null;
  }

  private startPersistentRarity(context: AudioContext, rarity: PersistentResultAmbience): void {
    if (this.muted || this.blocked || context.state !== 'running') return;
    if (this.activeResultAmbience === rarity && this.persistentRarityBus) return;
    const profile = getRarityAmbienceProfile(rarity);
    if (!profile.enabled) return;

    const previousFadeOutMs = this.activeResultAmbience
      ? getRarityAmbienceProfile(this.activeResultAmbience).fadeOutMs
      : 140;
    this.stopPersistentRarity(context, previousFadeOutMs, false);
    this.activeResultAmbience = rarity;
    this.desiredResultAmbience = rarity;
    this.setSteadyBaseMultiplier(context, profile.baseMixMultiplier, profile.fadeInMs);

    const now = context.currentTime;
    const bus = context.createGain();
    bus.gain.setValueAtTime(0.0001, now);
    bus.gain.linearRampToValueAtTime(profile.busGain, now + profile.fadeInMs / 1000);
    bus.connect(context.destination);
    this.persistentRarityBus = bus;

    const toneFilter = context.createBiquadFilter();
    toneFilter.type = 'lowpass';
    toneFilter.frequency.setValueAtTime(profile.toneLowpassHz, now);
    toneFilter.Q.setValueAtTime(0.65, now);
    const toneGain = context.createGain();
    toneGain.gain.setValueAtTime(profile.toneGain / Math.max(1, profile.toneFrequencies.length), now);
    toneGain.connect(toneFilter);
    toneFilter.connect(bus);

    profile.toneFrequencies.forEach((frequency, index) => {
      const oscillator = context.createOscillator();
      const panner = context.createStereoPanner();
      oscillator.type = index % 2 === 0 ? 'sine' : 'triangle';
      oscillator.frequency.setValueAtTime(frequency, now);
      oscillator.detune.setValueAtTime((index - (profile.toneFrequencies.length - 1) / 2) * 2.5, now);
      const side = index % 2 === 0 ? -1 : 1;
      panner.pan.setValueAtTime(side * profile.stereoSpread * Math.min(1, 0.45 + index * 0.12), now);
      oscillator.connect(panner);
      panner.connect(toneGain);
      oscillator.start(now);
      this.persistentRaritySources.push(oscillator);
    });

    const pulse = context.createOscillator();
    const pulseDepth = context.createGain();
    pulse.type = 'sine';
    pulse.frequency.setValueAtTime(profile.pulseRateHz, now);
    pulseDepth.gain.setValueAtTime(
      (profile.toneGain / Math.max(1, profile.toneFrequencies.length)) * profile.pulseDepth,
      now,
    );
    pulse.connect(pulseDepth);
    pulseDepth.connect(toneGain.gain);
    pulse.start(now);
    this.persistentRaritySources.push(pulse);

    if (profile.shimmerGain > 0) {
      const shimmer = context.createBufferSource();
      shimmer.buffer = this.getAmbienceNoiseBuffer(context);
      shimmer.loop = true;
      const shimmerBand = context.createBiquadFilter();
      shimmerBand.type = 'bandpass';
      shimmerBand.frequency.setValueAtTime(profile.shimmerBandHz, now);
      shimmerBand.Q.setValueAtTime(rarity === 'secret' ? 0.9 : 1.25, now);
      const shimmerGain = context.createGain();
      shimmerGain.gain.setValueAtTime(profile.shimmerGain, now);
      shimmer.connect(shimmerBand);
      shimmerBand.connect(shimmerGain);
      shimmerGain.connect(bus);
      shimmer.start(now + 0.11);
      this.persistentRaritySources.push(shimmer);
    }
  }

  private stopPersistentRarity(context: AudioContext, fadeMs: number, restoreBase: boolean): void {
    const bus = this.persistentRarityBus;
    const sources = this.persistentRaritySources;
    this.persistentRarityBus = null;
    this.persistentRaritySources = [];
    this.activeResultAmbience = null;
    if (bus) {
      const now = context.currentTime;
      bus.gain.cancelScheduledValues(now);
      bus.gain.setValueAtTime(Math.max(0.0001, bus.gain.value), now);
      bus.gain.exponentialRampToValueAtTime(0.0001, now + Math.max(0.03, fadeMs / 1000));
      for (const source of sources) {
        try {
          source.stop(now + Math.max(0.05, fadeMs / 1000 + 0.03));
        } catch {
          // Already-stopped sources are harmless during teardown/re-entry.
        }
      }
      window.setTimeout(() => {
        try {
          bus.disconnect();
        } catch {
          // The old local bus may already be disconnected during rapid re-entry.
        }
      }, fadeMs + 80);
    }
    if (restoreBase) this.setSteadyBaseMultiplier(context, 1, Math.max(180, fadeMs));
  }

  private getAmbienceNoiseBuffer(context: AudioContext): AudioBuffer {
    if (this.ambienceNoiseBuffer && this.ambienceNoiseBuffer.sampleRate === context.sampleRate) {
      return this.ambienceNoiseBuffer;
    }

    const seconds = 4;
    const length = Math.max(1, Math.floor(context.sampleRate * seconds));
    const buffer = context.createBuffer(1, length, context.sampleRate);
    const channel = buffer.getChannelData(0);
    let seed = 0x0a11d10f;
    for (let index = 0; index < channel.length; index += 1) {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      channel[index] = (seed / 0xffffffff) * 2 - 1;
    }
    const fadeLength = Math.min(Math.floor(context.sampleRate * 0.12), Math.floor(channel.length / 8));
    for (let index = 0; index < fadeLength; index += 1) {
      const mix = index / Math.max(1, fadeLength - 1);
      const tailIndex = channel.length - fadeLength + index;
      channel[tailIndex] = (channel[tailIndex] ?? 0) * (1 - mix) + (channel[index] ?? 0) * mix;
    }
    this.ambienceNoiseBuffer = buffer;
    return buffer;
  }

  private schedulePouchGrab(context: AudioContext): void {
    const now = context.currentTime;
    const noise = context.createBufferSource();
    noise.buffer = this.getChipNoiseBuffer(context);
    const band = context.createBiquadFilter();
    band.type = 'bandpass';
    band.frequency.setValueAtTime(3300, now);
    band.Q.setValueAtTime(1.35, now);
    const noiseGain = context.createGain();
    noiseGain.gain.setValueAtTime(0.0001, now);
    noiseGain.gain.exponentialRampToValueAtTime(0.043, now + 0.001);
    noiseGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.027);
    noise.connect(band);
    band.connect(noiseGain);
    noiseGain.connect(context.destination);
    noise.start(now);
    noise.stop(now + 0.032);

    const body = context.createOscillator();
    const bodyGain = context.createGain();
    body.type = 'triangle';
    body.frequency.setValueAtTime(430, now + 0.004);
    body.frequency.exponentialRampToValueAtTime(255, now + 0.052);
    bodyGain.gain.setValueAtTime(0.0001, now);
    bodyGain.gain.exponentialRampToValueAtTime(0.028, now + 0.005);
    bodyGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.055);
    body.connect(bodyGain);
    bodyGain.connect(context.destination);
    body.start(now + 0.004);
    body.stop(now + 0.06);
  }

  private scheduleChipClack(context: AudioContext): void {
    const now = context.currentTime;
    const variants = [0.92, 1.04, 0.97, 1.09, 1.0] as const;
    const variant = variants[this.chipClackIndex % variants.length] ?? 1;
    this.chipClackIndex += 1;

    const noise = context.createBufferSource();
    noise.buffer = this.getChipNoiseBuffer(context);
    const band = context.createBiquadFilter();
    band.type = 'bandpass';
    band.frequency.setValueAtTime(2350 * variant, now);
    band.Q.setValueAtTime(1.9, now);
    const noiseGain = context.createGain();
    noiseGain.gain.setValueAtTime(0.0001, now);
    noiseGain.gain.exponentialRampToValueAtTime(0.075, now + 0.0015);
    noiseGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.03);
    noise.connect(band);
    band.connect(noiseGain);
    noiseGain.connect(context.destination);
    noise.start(now);
    noise.stop(now + 0.036);

    const body = context.createOscillator();
    const bodyGain = context.createGain();
    body.type = 'triangle';
    body.frequency.setValueAtTime(1180 * variant, now);
    body.frequency.exponentialRampToValueAtTime(860 * variant, now + 0.024);
    bodyGain.gain.setValueAtTime(0.0001, now);
    bodyGain.gain.exponentialRampToValueAtTime(0.038, now + 0.001);
    bodyGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.026);
    body.connect(bodyGain);
    bodyGain.connect(context.destination);
    body.start(now);
    body.stop(now + 0.03);
  }

  private getChipNoiseBuffer(context: AudioContext): AudioBuffer {
    if (this.chipNoiseBuffer && this.chipNoiseBuffer.sampleRate === context.sampleRate) {
      return this.chipNoiseBuffer;
    }

    const length = Math.max(1, Math.floor(context.sampleRate * 0.04));
    const buffer = context.createBuffer(1, length, context.sampleRate);
    const channel = buffer.getChannelData(0);
    let seed = 0x5eed1234;
    for (let index = 0; index < channel.length; index += 1) {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      channel[index] = ((seed / 0xffffffff) * 2 - 1) * (1 - index / channel.length);
    }
    this.chipNoiseBuffer = buffer;
    return buffer;
  }
}

const gameAudio = new GameAudioController();

export const getGameAudio = (): GameAudioController => gameAudio;
