// Generated by tools/assets/build-runtime-bundles.mjs. Do not edit by hand.
export const RUNTIME_ART_BUNDLE_VERSION = 1 as const;
export const RUNTIME_ART_BUNDLE_TEXTURE_COUNT = 115 as const;
export const RUNTIME_ART_BUNDLES = [
  {
    "key": "runtime-art-bundle-01",
    "assetPath": "assets/bundles/runtime-art-01.mptpack",
    "textureCount": 19,
    "sourceBytes": 1491962,
    "packedBytes": 1494905
  },
  {
    "key": "runtime-art-bundle-02",
    "assetPath": "assets/bundles/runtime-art-02.mptpack",
    "textureCount": 19,
    "sourceBytes": 1487238,
    "packedBytes": 1490053
  },
  {
    "key": "runtime-art-bundle-03",
    "assetPath": "assets/bundles/runtime-art-03.mptpack",
    "textureCount": 21,
    "sourceBytes": 1491348,
    "packedBytes": 1494599
  },
  {
    "key": "runtime-art-bundle-04",
    "assetPath": "assets/bundles/runtime-art-04.mptpack",
    "textureCount": 19,
    "sourceBytes": 1491804,
    "packedBytes": 1494636
  },
  {
    "key": "runtime-art-bundle-05",
    "assetPath": "assets/bundles/runtime-art-05.mptpack",
    "textureCount": 19,
    "sourceBytes": 1486624,
    "packedBytes": 1489360
  },
  {
    "key": "runtime-art-bundle-06",
    "assetPath": "assets/bundles/runtime-art-06.mptpack",
    "textureCount": 18,
    "sourceBytes": 1483142,
    "packedBytes": 1485828
  }
] as const;
