from pathlib import Path

def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected 1 match, found {count}: {old[:100]!r}')
    p.write_text(text.replace(old, new, 1))

replace_once('src/game/data/presentation.ts', "import type { StandardRarity } from './collectibles';\n", "import type { GameLootPoolId, StandardRarity } from './collectibles';\n")
replace_once('src/game/data/presentation.ts', 'export interface PouchLayerPresentation {\n  x: number;\n  y: number;\n  displayWidth: number;\n}\n\nexport const POUCH_PRESENTATION = {\n', "export interface PouchLayerPresentation {\n  x: number;\n  y: number;\n  displayWidth: number;\n}\n\nexport type DropPouchMotif = 'spark' | 'video' | 'grid' | 'wave' | 'game' | 'scan';\n\nexport interface DropPouchSkin {\n  tint: number;\n  accent: number;\n  secondary: number;\n  motif: DropPouchMotif;\n}\n\nexport const DROP_POUCH_SKINS: Readonly<Record<GameLootPoolId, DropPouchSkin>> = {\n  'y2k-essentials': { tint: 0xffffff, accent: 0x9c7cff, secondary: 0x67e8ff, motif: 'spark' },\n  'video-link': { tint: 0xdff9ff, accent: 0x55e4ff, secondary: 0xff7ad9, motif: 'video' },\n  'pocket-office': { tint: 0xe8ffef, accent: 0x72f2ae, secondary: 0x8aa6ff, motif: 'grid' },\n  'pocket-audio': { tint: 0xffe7f3, accent: 0xff79bd, secondary: 0x8df8ff, motif: 'wave' },\n  'game-zone': { tint: 0xeee6ff, accent: 0xa985ff, secondary: 0x7bffcf, motif: 'game' },\n  'analog-nights': { tint: 0xffe8c8, accent: 0xffb65d, secondary: 0xff6f9f, motif: 'scan' },\n} as const;\n\nexport const getDropPouchSkin = (lootPoolId: GameLootPoolId): DropPouchSkin =>\n  DROP_POUCH_SKINS[lootPoolId];\n\nexport const POUCH_PRESENTATION = {\n")
replace_once('src/game/data/presentation.ts', '  body: { x: 0, y: 98, displayWidth: 420 } satisfies PouchLayerPresentation,\n', '  body: { x: 0, y: 98, displayWidth: 420 } satisfies PouchLayerPresentation,\n  // Authored Charged body has its visible mass ~17 source px to the right of\n  // Basic. Counter-shift optically aligns the two skins without rotating the pouch.\n  chargedBodyOpticalOffsetX: -7,\n  chargedBodyOpticalOffsetY: -2,\n')
replace_once('src/game/data/presentation.ts', '  bottomActionInset: 24,\n  selectorTopOffset: 164,\n', '  bottomActionInset: 24,\n  selectorTopOffset: 164,\n  dropSelectorBottomInset: 18,\n  dropSelectorHeight: 84,\n  dropSelectorMinWidth: 360,\n  dropSelectorMaxWidth: 470,\n  dropSelectorArrowHitWidth: 68,\n  dropSelectorSwipeThreshold: 34,\n  dropSelectorSwitchMs: 120,\n  tearHintIdleDelayMs: 5500,\n  tearHintNudgeAngle: 6,\n  tearHintNudgeRepeats: 2,\n')
replace_once('src/game/data/presentation.ts', '  discoveryPopScale: 1.035,\n  discoveryFrameWidth: 288,\n  discoveryFrameHeight: 208,\n  discoveryOutlineCopies: 8,\n  discoveryOutlineRadius: 3.2,\n  discoveryOutlineAlpha: 0.62,\n  discoveryLabelOffsetY: 120,\n  discoveryIntroMs: 220,\n  discoveryHoldMs: 90,\n  discoverySettleMs: 250,\n', '  // Every standard result gets a quiet silhouette presence. A NEW discovery\n  // layers the stronger transient discovery beat on top.\n  standardOutlineCopies: 4,\n  standardOutlineRadius: 2.2,\n  standardOutlineAlpha: 0.12,\n  standardOutlinePeakAlpha: 0.22,\n  newPersistentOutlineAlpha: 0.2,\n  newPersistentOutlinePeakAlpha: 0.34,\n  discoveryPopScale: 1.06,\n  discoveryFrameWidth: 288,\n  discoveryFrameHeight: 208,\n  discoveryOutlineCopies: 12,\n  discoveryOutlineRadius: 4.8,\n  discoveryOutlineAlpha: 0.86,\n  discoveryLabelOffsetY: 120,\n  discoveryIntroMs: 250,\n  discoveryHoldMs: 150,\n  discoverySettleMs: 290,\n')
replace_once('src/game/ui/openingVisuals.ts', "import { collectibleTextureKey, pouchStaticArtId, staticTextureKey, type PouchArtVariant } from '../data/artAssets';\nimport type { StandardRarity } from '../data/collectibles';\nimport {\n  getCollectiblePresentation,\n  MOTION_PRESENTATION,\n  POUCH_PRESENTATION,\n", "import { collectibleTextureKey, pouchStaticArtId, staticTextureKey, type PouchArtVariant } from '../data/artAssets';\nimport { DEFAULT_LOOT_POOL_ID, type GameLootPoolId, type StandardRarity } from '../data/collectibles';\nimport {\n  getCollectiblePresentation,\n  getDropPouchSkin,\n  MOTION_PRESENTATION,\n  POUCH_PRESENTATION,\n")
replace_once('src/game/ui/openingVisuals.ts', "const findTearHint = (root: Phaser.GameObjects.Container): Phaser.GameObjects.Text | null => {\n  const hint = root.getData('tearHint') as Phaser.GameObjects.Text | undefined;\n  return hint?.active ? hint : null;\n};\n\n", '')
replace_once('src/game/ui/openingVisuals.ts', "  y: number,\n  variant: PouchArtVariant = 'basic',\n): PouchVisual => {\n  const group = scene.add.container(x, y);\n", "  y: number,\n  variant: PouchArtVariant = 'basic',\n  lootPoolId: GameLootPoolId = DEFAULT_LOOT_POOL_ID,\n): PouchVisual => {\n  const group = scene.add.container(x, y);\n  const skin = getDropPouchSkin(lootPoolId);\n")
replace_once('src/game/ui/openingVisuals.ts', "  const bodyTexture = staticTextureKey(pouchStaticArtId(variant, 'body'));\n  if (scene.textures.exists(bodyTexture)) {\n    bodyLayer.add(body);\n    addPouchLayer(scene, bodyLayer, bodyTexture, POUCH_PRESENTATION.body);\n  } else {\n    addProceduralBody(scene, bodyLayer, body);\n  }\n\n  // There is deliberately no dark synthetic mouth. Opening is represented by\n", "  const bodyTexture = staticTextureKey(pouchStaticArtId(variant, 'body'));\n  if (scene.textures.exists(bodyTexture)) {\n    bodyLayer.add(body);\n    const bodyPresentation = variant === 'charged'\n      ? {\n          ...POUCH_PRESENTATION.body,\n          x: POUCH_PRESENTATION.body.x + POUCH_PRESENTATION.chargedBodyOpticalOffsetX,\n          y: POUCH_PRESENTATION.body.y + POUCH_PRESENTATION.chargedBodyOpticalOffsetY,\n        }\n      : POUCH_PRESENTATION.body;\n    addPouchLayer(scene, bodyLayer, bodyTexture, bodyPresentation).setTint(skin.tint);\n  } else {\n    addProceduralBody(scene, bodyLayer, body);\n  }\n\n  // Drop identity is a lightweight skin layer over the shared pouch geometry.\n  // It deliberately does not affect tear geometry, hitboxes or reward mechanics.\n  const skinLayer = scene.add.container(0, POUCH_PRESENTATION.body.y + 18);\n  const skinFrame = scene.add\n    .rectangle(0, 0, 282, 210, skin.accent, 0.035)\n    .setStrokeStyle(2, skin.accent, 0.2);\n  skinLayer.add(skinFrame);\n  const motif = scene.add.graphics().setAlpha(0.34);\n  motif.lineStyle(3, skin.accent, 0.72);\n  motif.fillStyle(skin.secondary, 0.55);\n  if (skin.motif === 'spark') {\n    motif.strokeCircle(0, -8, 45);\n    motif.lineBetween(-60, -8, 60, -8);\n    motif.lineBetween(0, -68, 0, 52);\n  } else if (skin.motif === 'video') {\n    motif.strokeRoundedRect(-58, -42, 116, 84, 12);\n    motif.fillTriangle(74, -26, 74, 26, 112, 0);\n  } else if (skin.motif === 'grid') {\n    for (let line = -54; line <= 54; line += 27) {\n      motif.lineBetween(line, -54, line, 54);\n      motif.lineBetween(-54, line, 54, line);\n    }\n  } else if (skin.motif === 'wave') {\n    motif.beginPath();\n    motif.moveTo(-86, 4);\n    motif.lineTo(-58, -22);\n    motif.lineTo(-30, 28);\n    motif.lineTo(0, -36);\n    motif.lineTo(30, 28);\n    motif.lineTo(58, -22);\n    motif.lineTo(86, 4);\n    motif.strokePath();\n  } else if (skin.motif === 'game') {\n    motif.strokeRoundedRect(-76, -38, 152, 76, 30);\n    motif.lineBetween(-48, 0, -18, 0);\n    motif.lineBetween(-33, -15, -33, 15);\n    motif.fillCircle(38, -10, 7);\n    motif.fillCircle(58, 10, 7);\n  } else {\n    for (let line = -54; line <= 54; line += 18) {\n      motif.lineBetween(-82, line, 82, line);\n    }\n    motif.strokeRoundedRect(-46, -58, 92, 116, 8);\n  }\n  skinLayer.add(motif);\n  bodyLayer.add(skinLayer);\n\n  // There is deliberately no dark synthetic mouth. Opening is represented by\n")
replace_once('src/game/ui/openingVisuals.ts', "  if (scene.textures.exists(stripTexture)) {\n    stripImage = addPouchLayer(scene, strip, stripTexture, POUCH_PRESENTATION.strip);\n  } else {\n", "  if (scene.textures.exists(stripTexture)) {\n    stripImage = addPouchLayer(scene, strip, stripTexture, POUCH_PRESENTATION.strip);\n    stripImage.setTint(skin.tint);\n  } else {\n")
replace_once('src/game/ui/openingVisuals.ts', "  if (scene.textures.exists(tabTexture)) {\n    addPouchLayer(scene, tab, tabTexture, POUCH_PRESENTATION.tab);\n  } else {\n", "  if (scene.textures.exists(tabTexture)) {\n    addPouchLayer(scene, tab, tabTexture, POUCH_PRESENTATION.tab).setTint(skin.tint);\n  } else {\n")
replace_once('src/game/ui/openingVisuals.ts', "  const hideHint = (): void => {\n    const hint = findTearHint(root);\n    if (!hint) return;\n    scene.tweens.killTweensOf(hint);\n    scene.tweens.add({ targets: hint, alpha: 0, duration: 90, ease: 'Sine.Out' });\n  };\n  const restoreHintAfterCancelledDrag = (): void => {\n    if (!group.active || tab.x >= tabEndX - 1) return;\n    const hint = findTearHint(root);\n    if (!hint) return;\n    scene.tweens.killTweensOf(hint);\n    scene.tweens.add({ targets: hint, alpha: 1, delay: 150, duration: 130, ease: 'Sine.Out' });\n  };\n  dragZone.on('pointerdown', hideHint);\n  scene.input.on('pointerup', restoreHintAfterCancelledDrag);\n  group.once('destroy', () => {\n    scene.input.off('pointerup', restoreHintAfterCancelledDrag);\n  });\n\n", '')
replace_once('src/i18n/en.ts', "    dropSwitchError: 'Could not switch Drop. Try again.',\n    tearHint: 'Drag the star to tear →',\n", "    dropSwitchError: 'Could not switch Drop. Try again.',\n    nextDrop: 'NEXT DROP →',\n    tearHint: 'Drag the star to tear →',\n")
replace_once('src/i18n/ru.ts', "    dropSwitchError: 'Не удалось переключить Drop. Попробуйте ещё раз.',\n    tearHint: 'Потяни звезду вправо →',\n", "    dropSwitchError: 'Не удалось переключить Drop. Попробуйте ещё раз.',\n    nextDrop: 'СЛЕДУЮЩИЙ DROP →',\n    tearHint: 'Потяни звезду вправо →',\n")
