import asyncio
from pathlib import Path
from playwright.async_api import async_playwright
OUT=Path('capture-probe');OUT.mkdir(exist_ok=True)
async def main():
 async with async_playwright() as pw:
  browser=await pw.chromium.launch(headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
  context=await browser.new_context(viewport={'width':1600,'height':900},locale='en-US')
  await context.add_init_script("sessionStorage.setItem('mystery-pocket-tech.debug-panel-collapsed','0')")
  page=await context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  await page.goto('http://127.0.0.1:4173/');await page.wait_for_timeout(4500)
  print('lang before',await page.locator('.mpt-debug-panel__meta').inner_text(),flush=True)
  await page.get_by_role('button',name='English',exact=True).click();await page.wait_for_timeout(4400)
  print('lang after',await page.locator('.mpt-debug-panel__meta').inner_text(),flush=True)
  s=await page.evaluate("JSON.parse(localStorage.getItem('mystery-pocket-tech.save'))")
  s.update({'chips':400,'totalOpens':15,'signal':0,'overchargeHundredths':100,'activeLootPoolId':'game-zone','pendingReveal':None,'onboarding':{'primaryCompleted':True,'firstRevealReceipt':None}})
  await page.evaluate("s => localStorage.setItem('mystery-pocket-tech.save',JSON.stringify(s))",s)
  await page.reload();await page.wait_for_timeout(4100)
  await page.add_style_tag(content='.mpt-debug-panel {display:none !important}')
  await page.screenshot(path=str(OUT/'01-game-basic.png'))
  await page.mouse.click(164,386);await page.wait_for_timeout(1000)
  await page.screenshot(path=str(OUT/'02-game-charged.png'))
  await page.mouse.move(599,227);await page.mouse.down();await page.mouse.move(761,226,steps=8)
  await page.screenshot(path=str(OUT/'03-drag-middle.png'))
  await page.mouse.move(990,225,steps=12)
  await page.screenshot(path=str(OUT/'04-drag-finish.png'))
  await page.mouse.up();await page.wait_for_timeout(800)
  await page.screenshot(path=str(OUT/'05-reveal-early.png'))
  await page.wait_for_timeout(3500);await page.screenshot(path=str(OUT/'06-reveal-settled.png'))
  print('save',await page.evaluate("JSON.parse(localStorage.getItem('mystery-pocket-tech.save'))"),flush=True)
  print('errors',errors,flush=True)
  await browser.close()
asyncio.run(main())
